# https://hub.docker.com/_/wordpress
---
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - data-db:/var/lib/mysql

  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - 8888:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - data-wp:/var/www/html

volumes:
  data-wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'volumes/wp'
  data-db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'volumes/db'